from .models import (
    DecisionStatus,
    DocumentResult,
    FoulEvent,
    FoulKind,
    ParticipantMark,
    PeriodResult,
    PeriodType,
    PlayerResult,
    ScoringEvent,
    ShotType,
    TeamFoulIndicator,
    TeamResult,
)
from .template import FECABA_V1, get_template
from .scoring import (
    InkColor,
    ScoreMarkKind,
    classify_score_mark,
    detect_jersey_circle,
    extract_scoring_events,
)
from .fouls import (
    TeamFoulCellKind,
    analyze_player_foul_row,
    classify_team_foul_cell,
    detect_half_separator,
    extract_player_fouls,
    extract_team_foul_indicators,
    parse_foul_symbol,
)
from .alterations import AlterationObservation, detect_alteration
from .pipeline import AnalysisContext, analyze_image, analyze_path
from .recognition import (
    HandwritingRecognizer,
    JerseyRecognitionAdapter,
    RecognitionCandidate,
    RecognitionResult,
    WriterProfile,
    apply_writer_profile,
    constrain_candidates,
)
from .reconcile import reconcile_document, reconcile_team
from .evaluation import (
    PredictionRecord,
    ThresholdMetrics,
    choose_acceptance_threshold,
    compare_known_unknown_writers,
    evaluate_threshold,
)

__all__ = [
    "DecisionStatus",
    "DocumentResult",
    "FoulEvent",
    "FoulKind",
    "ParticipantMark",
    "PeriodResult",
    "PeriodType",
    "PlayerResult",
    "ScoringEvent",
    "ShotType",
    "TeamFoulIndicator",
    "TeamResult",
    "FECABA_V1",
    "get_template",
    "InkColor",
    "ScoreMarkKind",
    "classify_score_mark",
    "detect_jersey_circle",
    "extract_scoring_events",
    "TeamFoulCellKind",
    "analyze_player_foul_row",
    "classify_team_foul_cell",
    "detect_half_separator",
    "extract_player_fouls",
    "extract_team_foul_indicators",
    "parse_foul_symbol",
    "AlterationObservation",
    "detect_alteration",
    "AnalysisContext",
    "analyze_image",
    "analyze_path",
    "HandwritingRecognizer",
    "JerseyRecognitionAdapter",
    "RecognitionCandidate",
    "RecognitionResult",
    "WriterProfile",
    "apply_writer_profile",
    "constrain_candidates",
    "reconcile_document",
    "reconcile_team",
    "PredictionRecord",
    "ThresholdMetrics",
    "choose_acceptance_threshold",
    "compare_known_unknown_writers",
    "evaluate_threshold",
]

__version__ = "0.1.0"
